from parameters import PtBinning, AK8TaggerWP

fit_parameters ={
    "baseline" : {
        "l"  : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2}
    },
    "msd40btagDDBvLV2Lwp_Pt-450to500" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Lwp_Pt-500to600" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Lwp_Pt-600toInf" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Mwp_Pt-450to500" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Mwp_Pt-500to600" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Mwp_Pt-600toInf" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Hwp_Pt-450to500" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Hwp_Pt-500to600" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40btagDDBvLV2Hwp_Pt-600toInf" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
    "msd40particleNetMD_Xbb_QCDHwp_Pt-450to500" : {
        "l"    : {"value" : 1, "lo" : 1, "hi" : 1},
        "b"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "bb"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "b+bb" : {"value" : 1, "lo" : 0, "hi" : 2},
        "c"    : {"value" : 1, "lo" : 0, "hi" : 2},
        "cc"   : {"value" : 1, "lo" : 0, "hi" : 2},
        "c+cc" : {"value" : 1, "lo" : 0, "hi" : 2},
    },
}